import React from 'react';
import { render, screen, waitFor } from '@testing-library/react';
import { BriefDisplay } from '@/components/BriefDisplay';

describe('BriefDisplay Component', () => {
  const mockBrief = 'This is a test trend. It is trending because of high engagement. It is popular on Reddit and YouTube.';
  const mockGeneratedAt = '2026-01-13T10:30:00Z';
  const mockOnClose = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should render brief text with proper formatting', () => {
    render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    // Check that all three sentences are rendered
    expect(screen.getByText(/This is a test trend\./i)).toBeInTheDocument();
    expect(screen.getByText(/It is trending because of high engagement\./i)).toBeInTheDocument();
    expect(screen.getByText(/It is popular on Reddit and YouTube\./i)).toBeInTheDocument();
  });

  it('should have light blue/purple background styling', () => {
    const { container } = render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    const briefBox = container.firstChild as HTMLElement;
    expect(briefBox).toHaveClass('bg-gradient-to-br');
    expect(briefBox).toHaveClass('from-blue-50');
    expect(briefBox).toHaveClass('via-purple-50');
    expect(briefBox).toHaveClass('to-blue-50');
  });

  it('should have border, padding, and rounded corners', () => {
    const { container } = render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    const briefBox = container.firstChild as HTMLElement;
    expect(briefBox).toHaveClass('border-2');
    expect(briefBox).toHaveClass('border-blue-200');
    expect(briefBox).toHaveClass('p-4');
    expect(briefBox).toHaveClass('rounded-lg');
  });

  it('should display "Generated by Claude AI" footer', () => {
    render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    expect(screen.getByText(/Generated by Claude AI/i)).toBeInTheDocument();
  });

  it('should have proper text formatting (gray-800, leading-relaxed)', () => {
    const { container } = render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    const textContainer = container.querySelector('.text-gray-800');
    expect(textContainer).toBeInTheDocument();
    expect(textContainer).toHaveClass('leading-relaxed');
  });

  it('should show "Cached" badge when cached=true', () => {
    render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={true}
        onClose={mockOnClose}
      />
    );

    const cachedBadge = screen.getByText('Cached');
    expect(cachedBadge).toBeInTheDocument();
    expect(cachedBadge).toHaveClass('bg-green-100');
    expect(cachedBadge).toHaveClass('text-green-700');
  });

  it('should not show "Cached" badge when cached=false', () => {
    render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    expect(screen.queryByText('Cached')).not.toBeInTheDocument();
  });

  it('should display formatted timestamp', () => {
    render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    // Check for time element with dateTime attribute
    const timeElement = screen.getByText(/Jan 13, 2026/i);
    expect(timeElement).toBeInTheDocument();
    expect(timeElement.closest('time')).toHaveAttribute('dateTime', mockGeneratedAt);
  });

  it('should have slide-down animation classes', () => {
    const { container } = render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    const briefBox = container.firstChild as HTMLElement;
    expect(briefBox).toHaveClass('transition-all');
    expect(briefBox).toHaveClass('duration-300');
    expect(briefBox).toHaveClass('ease-in-out');
  });

  it('should animate from hidden to visible on mount', async () => {
    const { container } = render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    const briefBox = container.firstChild as HTMLElement;

    // Initially should start hidden or transitioning
    // After animation delay, should be visible
    await waitFor(() => {
      expect(briefBox).toHaveClass('opacity-100');
      expect(briefBox).toHaveClass('translate-y-0');
    }, { timeout: 100 });
  });

  it('should have proper ARIA region role', () => {
    const { container } = render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    const briefBox = container.firstChild as HTMLElement;
    expect(briefBox).toHaveAttribute('role', 'region');
    expect(briefBox).toHaveAttribute('aria-label', 'Trend explanation');
  });

  it('should split brief into paragraphs by sentences', () => {
    render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    // Check that sentences are in separate paragraphs
    const paragraphs = screen.getAllByText(/\./);
    expect(paragraphs.length).toBeGreaterThanOrEqual(3); // At least 3 sentences
  });

  it('should handle brief with extra whitespace', () => {
    const messyBrief = '  This is sentence one  .   Sentence two here.  Final sentence.  ';

    render(
      <BriefDisplay
        brief={messyBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    expect(screen.getByText(/This is sentence one\./i)).toBeInTheDocument();
    expect(screen.getByText(/Sentence two here\./i)).toBeInTheDocument();
    expect(screen.getByText(/Final sentence\./i)).toBeInTheDocument();
  });

  it('should have footer with border and proper spacing', () => {
    const { container } = render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    const footer = container.querySelector('.border-t');
    expect(footer).toBeInTheDocument();
    expect(footer).toHaveClass('border-blue-200');
    expect(footer).toHaveClass('mt-4');
    expect(footer).toHaveClass('pt-3');
  });

  it('should display small gray text for footer (text-xs text-gray-500)', () => {
    const { container } = render(
      <BriefDisplay
        brief={mockBrief}
        generatedAt={mockGeneratedAt}
        cached={false}
        onClose={mockOnClose}
      />
    );

    const footer = container.querySelector('.text-xs.text-gray-500');
    expect(footer).toBeInTheDocument();
  });
});
