'use client';

import { useEffect, useState } from 'react';

/**
 * BriefDisplay Component (Story 4.2)
 * Displays AI-generated trend brief in a highlighted box
 * Features:
 * - Light blue/purple background with border
 * - 3-sentence formatting with paragraph spacing
 * - Footer: "Generated by Claude AI"
 * - Slide-down animation on mount, slide-up on unmount
 * - Shows cached indicator
 */

interface BriefDisplayProps {
  brief: string;
  generatedAt: string;
  cached: boolean;
  onClose: () => void;
}

export function BriefDisplay({
  brief,
  generatedAt,
  cached,
  onClose
}: BriefDisplayProps) {
  const [isVisible, setIsVisible] = useState(false);

  // Trigger slide-down animation on mount
  useEffect(() => {
    // Small delay to ensure animation plays
    const timer = setTimeout(() => setIsVisible(true), 10);
    return () => clearTimeout(timer);
  }, []);

  // Format the generated timestamp for display
  const formattedDate = new Date(generatedAt).toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true
  });

  return (
    <div
      className={`
        mt-4 p-4 rounded-lg border-2
        bg-gradient-to-br from-blue-50 via-purple-50 to-blue-50
        border-blue-200
        transition-all duration-300 ease-in-out
        ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 -translate-y-2'}
      `}
      role="region"
      aria-label="Trend explanation"
    >
      {/* Brief text */}
      <div className="text-gray-800 leading-relaxed text-sm space-y-2">
        {brief.split('.').filter(s => s.trim()).map((sentence, index) => (
          <p key={index} className="mb-1">
            {sentence.trim()}.
          </p>
        ))}
      </div>

      {/* Footer with metadata */}
      <div className="mt-4 pt-3 border-t border-blue-200 flex items-center justify-between text-xs text-gray-500">
        <div className="flex items-center space-x-2">
          {/* Claude AI Icon */}
          <svg
            className="w-4 h-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            aria-hidden="true"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
            />
          </svg>
          <span>Generated by Claude AI</span>
          {cached && (
            <span className="ml-2 px-2 py-0.5 bg-green-100 text-green-700 rounded-full text-xs font-medium">
              Cached
            </span>
          )}
        </div>
        <time dateTime={generatedAt} className="text-xs text-gray-400">
          {formattedDate}
        </time>
      </div>
    </div>
  );
}
