"""Initial schema: trends, data_collections, users, api_quota_usage

Revision ID: f59d3de35f66
Revises:
Create Date: 2026-01-08 10:58:56.008277+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f59d3de35f66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create data_collections table first (referenced by trends FK)
    op.create_table('data_collections',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('reddit_api_calls', sa.Integer(), nullable=True),
        sa.Column('youtube_api_quota_used', sa.Integer(), nullable=True),
        sa.Column('google_trends_api_calls', sa.Integer(), nullable=True),
        sa.CheckConstraint("status IN ('in_progress', 'completed', 'failed')", name='ck_data_collections_valid_status'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_data_collections'))
    )
    op.create_index('idx_started_at_desc', 'data_collections', ['started_at'], unique=False, postgresql_ops={'started_at': 'DESC'})

    # Create trends table
    op.create_table('trends',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('collection_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('reddit_score', sa.Integer(), nullable=True),
        sa.Column('reddit_comments', sa.Integer(), nullable=True),
        sa.Column('reddit_upvote_ratio', sa.Float(), nullable=True),
        sa.Column('reddit_subreddit', sa.String(length=100), nullable=True),
        sa.Column('youtube_views', sa.Integer(), nullable=True),
        sa.Column('youtube_likes', sa.Integer(), nullable=True),
        sa.Column('youtube_channel', sa.String(length=200), nullable=True),
        sa.Column('google_trends_interest', sa.Integer(), nullable=True),
        sa.Column('google_trends_related_queries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('similarweb_traffic', sa.Integer(), nullable=True),
        sa.Column('similarweb_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('reddit_velocity_score', sa.Float(), nullable=True),
        sa.Column('youtube_traction_score', sa.Float(), nullable=True),
        sa.Column('google_trends_spike_score', sa.Float(), nullable=True),
        sa.Column('similarweb_bonus_applied', sa.Boolean(), nullable=True),
        sa.Column('momentum_score', sa.Float(), nullable=True),
        sa.Column('confidence_level', sa.String(length=10), nullable=True),
        sa.Column('ai_brief', sa.Text(), nullable=True),
        sa.Column('ai_brief_generated_at', sa.TIMESTAMP(), nullable=True),
        sa.CheckConstraint("confidence_level IN ('high', 'medium', 'low')", name='ck_trends_valid_confidence'),
        sa.ForeignKeyConstraint(['collection_id'], ['data_collections.id'], name=op.f('fk_trends_collection_id_data_collections'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_trends'))
    )
    op.create_index('idx_confidence_level', 'trends', ['confidence_level'], unique=False)
    op.create_index('idx_created_at_desc', 'trends', ['created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_momentum_score_desc', 'trends', [sa.text('momentum_score DESC')], unique=False)
    op.create_index(op.f('ix_collection_id'), 'trends', ['collection_id'], unique=False)
    op.create_index(op.f('ix_momentum_score'), 'trends', ['momentum_score'], unique=False)

    # Create users table
    op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_login', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
        sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index(op.f('ix_username'), 'users', ['username'], unique=False)

    # Create api_quota_usage table
    op.create_table('api_quota_usage',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('api_name', sa.String(length=50), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('units_used', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_api_quota_usage')),
        sa.UniqueConstraint('api_name', 'date', name='uq_api_quota_usage_api_name_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_quota_usage')
    op.drop_index(op.f('ix_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_momentum_score'), table_name='trends')
    op.drop_index(op.f('ix_collection_id'), table_name='trends')
    op.drop_index('idx_momentum_score_desc', table_name='trends')
    op.drop_index('idx_created_at_desc', table_name='trends')
    op.drop_index('idx_confidence_level', table_name='trends')
    op.drop_table('trends')
    op.drop_index('idx_started_at_desc', table_name='data_collections')
    op.drop_table('data_collections')
    # ### end Alembic commands ###
